name: Python Package using Anaconda

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Checkout repository
    - name: Checkout repository
      uses: actions/checkout@v3

    # Set up Miniconda
    - name: Set up Miniconda
      uses: conda-incubator/setup-miniconda@v2
      with:
        activate-environment: test-env
        python-version: 3.8
        environment-file: environment.yml
        auto-activate-base: false

    # Install dependencies
    - name: Install dependencies
      run: |
        conda install pytest
        conda install -c conda-forge pylint

    # Run tests
    - name: Run tests
      run: pytest

    # Perform linting
    - name: Run linting
      run: pylint Python Package using Anaconda
